// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package T5_ej2;

/************************************************************/
/**
 * 
 */
public class Autor {
	/**
	 * 
	 */
	private String nombre;
	/**
	 * 
	 */
	private String nacionalidad;
	/**
	 * 
	 */
	private EDate fecha_nacim;
}
