// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package T5_ej2;

/************************************************************/
/**
 * 
 */
public class Lector {
	/**
	 * 
	 */
	public Copias[] copias;
	/**
	 * 
	 */
	private int libros_prestados;
	/**
	 * 
	 */
	private boolean multa;
	/**
	 * 
	 */
	private int id_lector;
}
