// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package T5_ej2;

/************************************************************/
/**
 * 
 */
public abstract class Libros {
	/**
	 * 
	 */
	private String nombre;
	/**
	 * 
	 */
	private String editorial;
	/**
	 * 
	 */
	private EDate anyo;
	/**
	 * 
	 */
	private String autor;
	/**
	 * 
	 */
	private String categoria;
}
