// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package T5_ej2;

/************************************************************/
/**
 * 
 */
public class Prestamo {
	/**
	 * 
	 */
	private EDate fecha_inicio;
	/**
	 * 
	 */
	private boolean multa;
	/**
	 * 
	 */
	private EDate fecha_fin;

	/**
	 * 
	 * @param id_copia 
	 * @param id_lector 
	 */
	public void prestar(int id_copia, int id_lector) {
	}
}
